# Generated by CMake, DO NOT EDIT
/Users/mclifton/Downloads/openal-soft-1.17.2/CMakeFiles/cmake.check_cache: \
/Applications/CMake.app/Contents/share/cmake-3.5/Modules/CMakeParseArguments.cmake\
/Applications/CMake.app/Contents/share/cmake-3.5/Modules/CMakePushCheckState.cmake\
/Applications/CMake.app/Contents/share/cmake-3.5/Modules/CheckCXXSymbolExists.cmake\
/Applications/CMake.app/Contents/share/cmake-3.5/Modules/CheckSymbolExists.cmake\
/Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake\
/Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindPackageMessage.cmake\
/Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindQt4.cmake\
/Applications/CMake.app/Contents/share/cmake-3.5/Modules/MacroAddFileDependencies.cmake\
/Users/mclifton/Downloads/openal-soft-1.17.2/utils/alsoft-config/CMakeLists.txt
	/Applications/CMake.app/Contents/bin/cmake -H/Users/mclifton/Downloads/openal-soft-1.17.2 -B/Users/mclifton/Downloads/openal-soft-1.17.2
